spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:10271"
              - "http://localhost:10272"
              - "http://localhost:10273"
              - "http://localhost:10274"
              - "http://localhost:10275"
              - "http://localhost:10276"
              - "http://localhost:10277"
              - "http://localhost:10278"
              - "http://localhost:10279"
              - "https://javame.live"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: auth-api
          uri: lb://AUTH-API
          predicates:
            - Path=/api/auth/**

        - id: member-api
          uri: lb://MEMBER-API
          predicates:
            - Path=/api/v1/login/**

        - id: environment-api
          uri: lb://ENVIRONMENT-API
          predicates:
            - Path=/api/v1/environment/**
