spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:10271"
              - "http://localhost:10272"
              - "http://localhost:10273"
              - "http://localhost:10274"
              - "http://localhost:10275"
              - "http://localhost:10276"
              - "http://localhost:10277"
              - "http://localhost:10278"
              - "http://localhost:10279"
              - "https://javame.live"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: auth-api
          uri: lb://AUTH-API
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /$\{segment}

        - id: member-api
          uri: lb://MEMBER-API
          predicates:
            - Path=/api/v1/login/**
          filters:
            - RewritePath=/api/v1/login/(?<segment>.*), /$\{segment}

        - id: environment-api
          uri: lb://ENVIRONMENT-API
          predicates:
            - Path=/api/v1/environment/**
          filters:
            - RewritePath=/api/v1/environment/(?<segment>.*), /$\{segment}

        - id: rule-api
          uri: lb://RULE-API
          predicates:
            - Path=/api/v1/rule/**
          filters:
            - RewritePath=/api/v1/rule/(?<segment>.*), /$\{segment}

        - id: ai-api
          uri: lb://AI-API
          predicates:
            - Path=/api/v1/ai/**
          filters:
            - RewritePath=/api/v1/ai/(?<segment>.*), /$\{segment}
